apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: vol_interactions
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 300Gi
  storageClassName: standard